pipeline {
    agent any

    tools {
        // Use the name you configured for the Docker installation
        dockerTool 'MyDocker'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Use the Docker tool
                    docker.image('node:14').inside {
                        sh 'npm install'
                    }
                }
            }
        }
    }
}
