pipeline {
    agent any
    ACCOUNT_ID = ''
    AWS_REGION = 'us-east-1'

    stages {
        stage('Hello Stage') {
                            script {
                    // Cloning a Git repository with options
                    def gitOptions = [
                        credentialsId: 'PGHAT', // Optional: Use specific credentials from Jenkins
                        url: 'https://github.com/Yummy12345678/gatsby-testing.git',
                        branch: 'main', // Optional: Specify a specific branch
                        changelog: true // Optional: Include changelog in build
                    ]
                    git gitOptions
                }
        }
    }
}
